version: "3"
services:
  db:
    container_name: mysql 
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: root 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INITDB_SKIP_TZINFO: 1
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
